- name: Hello World Sample
  hosts: all
  gather_facts: True
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello WORLD - from Github!"

- name: Print all available facts
  ansible.builtin.debug:
    var: ansible_facts