- name: Hello World Sample
  hosts: all
  gather_facts: True
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello WORLD - from Github!"
#    - debug:
#        var: ansible_facts
- name: Ensure the httpd service is running
  service:
    name: httpd
    state: started
  become: yes        