- name: Hello World Sample
  hosts: all
  gather_facts: True
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello WORLD - from Github!"
#    - debug:
#        var: ansible_facts
    - name: Ensure the cron service is running
      service:
        name: cron
        state: started
      become: yes        